@server=http://localhost:4004
@username=alice
@password=


### Customer
# @name Customer_GET
GET {{server}}/odata/v4/customer/Customer
Authorization: Basic {{username}}:{{password}}


### Customer
# @name Customer_POST
POST {{server}}/odata/v4/customer/Customer
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "name": "name-5418534",
  "phone": "phone-5418534",
  "address": "address-5418534"
}


### Customer
# @name Customer_PATCH
PATCH {{server}}/odata/v4/customer/Customer/undefined
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "name": "name-5418534",
  "phone": "phone-5418534",
  "address": "address-5418534"
}


### Customer
# @name Customer_DELETE
DELETE {{server}}/odata/v4/customer/Customer/undefined
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
