@server=http://localhost:4004
@username=alice
@password=


### Customer
# @name Customer_GET
GET {{server}}/odata/v4/customer/Customer
Authorization: Basic {{username}}:{{password}}


### Customer
# @name Customer_POST
POST {{server}}/odata/v4/customer/Customer
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "name": "Misia",
  "phone": "+48 666 676 769",
  "address": "Wroclaw"
}


### Customer
# @name Customer_PATCH
PATCH {{server}}/odata/v4/customer/Customer/9b18489b-55a6-411d-94df-dc0f358f953f
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "name": "Lexo Tevdorashvili"
}


### Customer
# @name Customer_DELETE
DELETE {{server}}/odata/v4/customer/Customer/13124458-0007-4509-bbff-39250de8821f
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
