@server=http://localhost:4004
@username=alice
@password=


### Employee
# @name Employee_GET
GET {{server}}/odata/v4/employee/Employee
Authorization: Basic {{username}}:{{password}}


### Employee
# @name Employee_POST
POST {{server}}/odata/v4/employee/Employee
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "28919394-d287-4c81-bed7-d8937c007cc0",
  "name": "name-28919394",
  "role": "Delivery",
  "createdAt": "2007-10-28T20:00:00.000Z",
  "createdBy": "createdBy.h7uci@example.com",
  "modifiedAt": "2016-02-22T20:00:00.000Z",
  "modifiedBy": "modifiedBy.h7uci@example.com"
}


### Employee
# @name Employee_PATCH
PATCH {{server}}/odata/v4/employee/Employee/28919394-d287-4c81-bed7-d8937c007cc0
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "28919394-d287-4c81-bed7-d8937c007cc0",
  "name": "name-28919394",
  "role": "Delivery",
  "createdAt": "2007-10-28T20:00:00.000Z",
  "createdBy": "createdBy.h7uci@example.com",
  "modifiedAt": "2016-02-22T20:00:00.000Z",
  "modifiedBy": "modifiedBy.h7uci@example.com"
}


### Employee
# @name Employee_DELETE
DELETE {{server}}/odata/v4/employee/Employee/28919394-d287-4c81-bed7-d8937c007cc0
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
