@server=http://localhost:4004
@username=alice
@password=


### Expense
# @name Expense_GET
GET {{server}}/odata/v4/expense/Expense
Authorization: Basic {{username}}:{{password}}


### Expense
# @name Expense_POST
POST {{server}}/odata/v4/expense/Expense
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "11942182-0deb-4077-83c7-3a0508c3acfc",
  "description": "description-11942182",
  "amount": 38.47,
  "date": "2022-04-05T20:00:00.000Z",
  "category": "Delivery"
}


### Expense
# @name Expense_PATCH
PATCH {{server}}/odata/v4/expense/Expense/11942182-0deb-4077-83c7-3a0508c3acfc
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "11942182-0deb-4077-83c7-3a0508c3acfc",
  "description": "description-11942182",
  "amount": 38.47,
  "date": "2022-04-05T20:00:00.000Z",
  "category": "Delivery"
}


### Expense
# @name Expense_DELETE
DELETE {{server}}/odata/v4/expense/Expense/11942182-0deb-4077-83c7-3a0508c3acfc
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
