@server=http://localhost:4004
@username=alice
@password=


### Expense
# @name Expense_GET
GET {{server}}/odata/v4/expense/Expense
Authorization: Basic {{username}}:{{password}}


### Expense
# @name Expense_POST
POST {{server}}/odata/v4/expense/Expense
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "26508756-981e-4c3d-873c-7e55aa9f4ff6",
  "description": "description-26508756",
  "amount": 53.09,
  "date": "2008-01-09T23:00:00.000Z",
  "category": "Other"
}


### Expense
# @name Expense_PATCH
PATCH {{server}}/odata/v4/expense/Expense/26508756-981e-4c3d-873c-7e55aa9f4ff6
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "26508756-981e-4c3d-873c-7e55aa9f4ff6",
  "description": "description-26508756",
  "amount": 53.09,
  "date": "2008-01-09T23:00:00.000Z",
  "category": "Other"
}


### Expense
# @name Expense_DELETE
DELETE {{server}}/odata/v4/expense/Expense/26508756-981e-4c3d-873c-7e55aa9f4ff6
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
