@server=http://localhost:4004
@username=alice
@password=


### Product
# @name Product_GET
GET {{server}}/odata/v4/product/Product
Authorization: Basic {{username}}:{{password}}


### Product
# @name Product_POST
POST {{server}}/odata/v4/product/Product
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "31335706-d6d7-4c36-a237-95fcc2513948",
  "name": "name-31335706",
  "stock": 4,
  "price": 70.9,
  "lastStocked": "2007-01-12T20:00:00.000Z",
  "createdAt": "2017-07-14T20:00:00.000Z",
  "createdBy": "createdBy.inmsa@example.org",
  "modifiedAt": "2005-03-24T20:00:00.000Z",
  "modifiedBy": "modifiedBy.inmsa@example.com"
}


### Product
# @name Product_PATCH
PATCH {{server}}/odata/v4/product/Product/31335706-d6d7-4c36-a237-95fcc2513948
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "31335706-d6d7-4c36-a237-95fcc2513948",
  "name": "name-31335706",
  "stock": 4,
  "price": 70.9,
  "lastStocked": "2007-01-12T20:00:00.000Z",
  "createdAt": "2017-07-14T20:00:00.000Z",
  "createdBy": "createdBy.inmsa@example.org",
  "modifiedAt": "2005-03-24T20:00:00.000Z",
  "modifiedBy": "modifiedBy.inmsa@example.com"
}


### Product
# @name Product_DELETE
DELETE {{server}}/odata/v4/product/Product/31335706-d6d7-4c36-a237-95fcc2513948
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
