@server=http://localhost:4004
@username=alice
@password=


### Product
# @name Product_GET
GET {{server}}/odata/v4/sales/Product
Authorization: Basic {{username}}:{{password}}


### Product
# @name Product_POST
POST {{server}}/odata/v4/sales/Product
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "18147500-05c5-4deb-8a73-faec7af0674e",
  "name": "name-18147500",
  "stock": 83,
  "price": 46275557.18,
  "currency": "500",
  "costPrice": 26.3
}


### Product
# @name Product_PATCH
PATCH {{server}}/odata/v4/sales/Product/18147500-05c5-4deb-8a73-faec7af0674e
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "18147500-05c5-4deb-8a73-faec7af0674e",
  "name": "name-18147500",
  "stock": 83,
  "price": 46275557.18,
  "currency": "500",
  "costPrice": 26.3
}


### Product
# @name Product_DELETE
DELETE {{server}}/odata/v4/sales/Product/18147500-05c5-4deb-8a73-faec7af0674e
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Order
# @name Order_GET
GET {{server}}/odata/v4/sales/Order
Authorization: Basic {{username}}:{{password}}


### Order
# @name Order_POST
POST {{server}}/odata/v4/sales/Order
Content-Type: application/json
Authorization: Basic giorgi:123

{
  "items": [
    {
      "product": {
        "ID": "550e8400-e29b-41d4-a716-446655440002"
      },
      "quantity": 45
    },
    {
      "product": {
        "ID": "550e8400-e29b-41d4-a716-446655440003"
      },
      "quantity": 8
    }
  ]
}


### Order
# @name Order_PATCH
PATCH {{server}}/odata/v4/sales/Order/95357447-444d-47cd-8c96-edb13d115082
Content-Type: application/json
Authorization: Basic giorgi:123

{
  "items": [
    {
      "product": {
        "ID": "550e8400-e29b-41d4-a716-446655440001"
      },
      "quantity": 45
    },
    {
      "product": {
        "ID": "550e8400-e29b-41d4-a716-446655440002"
      },
      "quantity": 8
    }
  ]
}


### Order
# @name Order_DELETE
DELETE {{server}}/odata/v4/sales/Order/95357447-444d-47cd-8c96-edb13d115082
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
