@server=http://localhost:4004
@username=alice
@password=


### Product
# @name Product_GET
GET {{server}}/odata/v4/sales/Product
Authorization: Basic {{username}}:{{password}}


### Product
# @name Product_POST
POST {{server}}/odata/v4/sales/Product
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "name": "Parówki dla Jupi",
  "price": 10,
  "stock": 21
}


### Product
# @name Product_PATCH
PATCH {{server}}/odata/v4/sales/Product/d256dd29-a1c7-4187-85fc-71361b91e318
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "stock": 5
}


### Product
# @name Product_DELETE
DELETE {{server}}/odata/v4/sales/Product/28736635-be8b-4719-a53e-b370bcd175df
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}


### Order
# @name Order_GET
GET {{server}}/odata/v4/sales/Order
Authorization: Basic {{username}}:{{password}}


### Order
# @name Order_POST
POST {{server}}/odata/v4/sales/Order
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "customer": {
    "ID": "3492bac3-baba-47a5-876a-7baf6fb16f7e"
  },
  "deliverer": {
    "ID": "21a63816-ec8d-429d-a422-3e09481fc35d"
  },
  "items": [
    {
      "product": {
        "ID": "33b4c26d-7a90-48a1-bf7b-6cc22477d62d"
      },
      "quantity": 4
    }
  ]
}

### Order
# @name Order_PATCH
PATCH {{server}}/odata/v4/sales/Order/15284027-c1cc-4aeb-8668-79fbca622643
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}

{
  "ID": "15284027-c1cc-4aeb-8668-79fbca622643",
  "customer": {
    "ID": "19992064-d275-4c10-a1dd-49bb94f8bb35"
  },
  "deliverer": {
    "ID": "15342713-7fb4-4d80-875a-55c78e66c693"
  },
  "orderDate": "2004-06-05T23:00:00.000Z",
  "status": "Delivered",
  "total": 45.68,
  "deliveryFee": 67.05,
  "items": [
    {
      "ID": "15487066-382e-46fa-b0c3-2e97a9ac856d",
      "product": {
        "ID": "70048587-44aa-4a01-8e12-d982441071a2"
      },
      "quantity": 46,
      "unitPrice": 84.08,
      "subtotal": 50.31,
      "createdAt": "2001-06-12T23:00:00.000Z",
      "createdBy": "createdBy.97xwa@example.com",
      "modifiedAt": "2021-03-21T23:00:00.000Z",
      "modifiedBy": "modifiedBy.97xwa@example.net"
    },
    {
      "ID": "15487067-7eab-4868-bce1-ac5edbe57fff",
      "product": {
        "ID": "28736635-be8b-4719-a53e-b370bcd175df"
      },
      "quantity": 1,
      "unitPrice": 3.95,
      "subtotal": 60.17,
      "createdAt": "2015-11-17T23:00:00.000Z",
      "createdBy": "createdBy.97xwb@example.net",
      "modifiedAt": "2006-07-16T23:00:00.000Z",
      "modifiedBy": "modifiedBy.97xwb@example.net"
    }
  ],
  "createdAt": "2019-09-14T23:00:00.000Z",
  "createdBy": "createdBy.93l8b@example.net",
  "modifiedAt": "2007-03-09T23:00:00.000Z",
  "modifiedBy": "modifiedBy.93l8b@example.com"
}


### Order
# @name Order_DELETE
DELETE {{server}}/odata/v4/sales/Order/15284027-c1cc-4aeb-8668-79fbca622643
Content-Type: application/json
Authorization: Basic {{username}}:{{password}}
